// <auto-generated />
using System;
using Logbook.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace logbook.Migrations
{
    [DbContext(typeof(LogbookDBContext))]
    partial class LogbookDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GroupUser", b =>
                {
                    b.Property<Guid>("GroupsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("char(36)");

                    b.HasKey("GroupsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("GroupUser");
                });

            modelBuilder.Entity("Logbook.Models.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Organizer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Logbook.Models.EventAttendance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("EventAttendance");
                });

            modelBuilder.Entity("Logbook.Models.EventTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ShowAs")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("EventTemplate");
                });

            modelBuilder.Entity("Logbook.Models.EventTemplateSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AttendingId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("DifferentiateOnAttendance")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("TentativeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UnavailableId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("AttendingId");

                    b.HasIndex("TentativeId");

                    b.HasIndex("UnavailableId");

                    b.ToTable("EventTemplateSet");
                });

            modelBuilder.Entity("Logbook.Models.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time(6)");

                    b.Property<Guid>("EventTemplateSetId")
                        .HasColumnType("char(36)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("char(36)");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time(6)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EventTemplateSetId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Logbook.Models.PersonalEventTemplateSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("EventTemplateSetId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("EventTemplateSetId");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("PersonalEventTemplateSet");
                });

            modelBuilder.Entity("Logbook.Models.Registration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LinkedAccount")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Registration");
                });

            modelBuilder.Entity("Logbook.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("AliasMatchingType")
                        .HasColumnType("int");

                    b.Property<string>("CalendarName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("CalendarRegistrationId")
                        .HasColumnType("char(36)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("OneDriveRegistrationId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CalendarRegistrationId");

                    b.HasIndex("OneDriveRegistrationId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GroupUser", b =>
                {
                    b.HasOne("Logbook.Models.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Logbook.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Logbook.Models.Event", b =>
                {
                    b.HasOne("Logbook.Models.Group", "Group")
                        .WithMany("Events")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Logbook.Models.EventAttendance", b =>
                {
                    b.HasOne("Logbook.Models.Event", null)
                        .WithMany("EventAttendances")
                        .HasForeignKey("EventId");
                });

            modelBuilder.Entity("Logbook.Models.EventTemplateSet", b =>
                {
                    b.HasOne("Logbook.Models.EventTemplate", "Attending")
                        .WithMany()
                        .HasForeignKey("AttendingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Logbook.Models.EventTemplate", "Tentative")
                        .WithMany()
                        .HasForeignKey("TentativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Logbook.Models.EventTemplate", "Unavailable")
                        .WithMany()
                        .HasForeignKey("UnavailableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attending");

                    b.Navigation("Tentative");

                    b.Navigation("Unavailable");
                });

            modelBuilder.Entity("Logbook.Models.Group", b =>
                {
                    b.HasOne("Logbook.Models.EventTemplateSet", "EventTemplateSet")
                        .WithMany()
                        .HasForeignKey("EventTemplateSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventTemplateSet");
                });

            modelBuilder.Entity("Logbook.Models.PersonalEventTemplateSet", b =>
                {
                    b.HasOne("Logbook.Models.EventTemplateSet", "EventTemplateSet")
                        .WithMany()
                        .HasForeignKey("EventTemplateSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Logbook.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Logbook.Models.User", "User")
                        .WithMany("PersonalEventTemplates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventTemplateSet");

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Logbook.Models.User", b =>
                {
                    b.HasOne("Logbook.Models.Registration", "CalendarRegistration")
                        .WithMany()
                        .HasForeignKey("CalendarRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Logbook.Models.Registration", "OneDriveRegistration")
                        .WithMany()
                        .HasForeignKey("OneDriveRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalendarRegistration");

                    b.Navigation("OneDriveRegistration");
                });

            modelBuilder.Entity("Logbook.Models.Event", b =>
                {
                    b.Navigation("EventAttendances");
                });

            modelBuilder.Entity("Logbook.Models.Group", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Logbook.Models.User", b =>
                {
                    b.Navigation("PersonalEventTemplates");
                });
#pragma warning restore 612, 618
        }
    }
}
